variable "aws_cognito_identity_pool_id" {}
variable "aws_cognito_identity_provider" {}
variable "aws_region" {}
variable "dynamodb_table_name" {}
variable "environment" {}
variable "github_connection_arn" {}
variable "spackle_aws_access_key_id" {}
variable "spackle_aws_secret_access_key" {}
variable "supabase_jwt_secret" {}
