[build]
  command = "yarn build"
  functions = "netlify/functions"
  publish = ".next"

[[headers]]
  for = "/api/stripe/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[functions]
  external_node_modules = ["@sentry/serverless"]

[[redirects]]
  from = "/api/*"
  to = "https://api.spackle.so/:splat"
  status = 200

[[redirects]]
  from = "/docs"
  to = "https://docs.spackle.so"
  status = 301
  force = true