[build]
  base = "apps/web"
  command = "yarn build"
  functions = "netlify/functions"
  publish = "apps/web/.next"

[[headers]]
  for = "/api/stripe/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[functions]
  external_node_modules = ["@sentry/serverless"]