[build]
  command = "next build"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"
  publish = ".next"

[[headers]]
  for = "/api/stripe/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[functions]
  external_node_modules = ["@sentry/serverless"]