[build]
  command = "next build"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"
  publish = ".next"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[edge_functions]]
  path = "/edge/customers/*/state"
  function = "customer_state"
  external_node_modules = ["@sentry/serverless"]