[build]
  command = "next build"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"
  publish = ".next"

[[headers]]
  for = "/api/stripe/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[edge_functions]]
  path = "/edge/customers/*/state"
  function = "customer_state"

[functions]
  external_node_modules = ["@sentry/serverless"]

[[redirects]]
  from = "https://edge.spackle.so/*"
  to = "https://www.spackle.so/edge/:splat"
  status = 200

[[redirects]]
  from = "https://api.spackle.so/*"
  to = "https://www.spackle.so/api/:splat"
  status = 200
