-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
ALTER TABLE
    IF EXISTS public.stripe_accounts
ADD
    COLUMN secret_key uuid DEFAULT uuid_generate_v4();

ALTER TABLE
    IF EXISTS public.stripe_accounts
ADD
    CONSTRAINT stripe_accounts_secret_key_key UNIQUE (secret_key);

UPDATE
    public.stripe_accounts
SET
    secret_key = uuid_generate_v4()
where
    secret_key is null;