-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.tokens
    ADD COLUMN stripe_account_id text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.tokens
    ADD CONSTRAINT tokens_stripe_account_id_fkey FOREIGN KEY (stripe_account_id)
    REFERENCES public.stripe_accounts (stripe_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
