create table "public"."stripe_invoices" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "stripe_id" text not null,
    "stripe_account_id" text not null,
    "stripe_json" json,
    "status" text not null,
    "stripe_customer_id" text not null,
    "total" bigint not null
);


alter table "public"."stripe_invoices" enable row level security;

CREATE UNIQUE INDEX stripe_invoices_pkey ON public.stripe_invoices USING btree (id);

CREATE UNIQUE INDEX stripe_invoices_stripe_id_key ON public.stripe_invoices USING btree (stripe_id);

alter table "public"."stripe_invoices" add constraint "stripe_invoices_pkey" PRIMARY KEY using index "stripe_invoices_pkey";

alter table "public"."stripe_invoices" add constraint "stripe_invoices_stripe_account_id_fkey" FOREIGN KEY (stripe_account_id) REFERENCES stripe_accounts(stripe_id) not valid;

alter table "public"."stripe_invoices" validate constraint "stripe_invoices_stripe_account_id_fkey";

alter table "public"."stripe_invoices" add constraint "stripe_invoices_stripe_customer_id_fkey" FOREIGN KEY (stripe_customer_id) REFERENCES stripe_customers(stripe_id) not valid;

alter table "public"."stripe_invoices" validate constraint "stripe_invoices_stripe_customer_id_fkey";

alter table "public"."stripe_invoices" add constraint "stripe_invoices_stripe_id_key" UNIQUE using index "stripe_invoices_stripe_id_key";


