create table "public"."stripe_users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "email" text,
    "name" text,
    "stripe_account_id" text not null,
    "stripe_id" text not null,
    CONSTRAINT stripe_users_stripe_account_id_stripe_id_feat_key UNIQUE (
        stripe_account_id,
        stripe_id
    )
);

alter table
    "public"."stripe_accounts"
add
    column "name" text;

CREATE UNIQUE INDEX stripe_users_pkey ON public.stripe_users USING btree (id);

alter table
    "public"."stripe_users"
add
    constraint "stripe_users_pkey" PRIMARY KEY using index "stripe_users_pkey";

alter table
    "public"."stripe_users"
add
    constraint "stripe_users_stripe_account_id_fkey" FOREIGN KEY (stripe_account_id) REFERENCES stripe_accounts(stripe_id) not valid;

alter table
    "public"."stripe_users" validate constraint "stripe_users_stripe_account_id_fkey";