create table "public"."stripe_invoice_line_items" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "stripe_id" text not null,
    "stripe_account_id" text not null,
    "stripe_json" json,
    "amount" bigint not null,
    "type" text not null,
    "stripe_invoice_id" text not null
);


alter table "public"."stripe_invoice_line_items" enable row level security;

CREATE UNIQUE INDEX stripe_invoice_line_items_pkey ON public.stripe_invoice_line_items USING btree (id);

CREATE UNIQUE INDEX stripe_invoice_line_items_stripe_id_key ON public.stripe_invoice_line_items USING btree (stripe_id);

alter table "public"."stripe_invoice_line_items" add constraint "stripe_invoice_line_items_pkey" PRIMARY KEY using index "stripe_invoice_line_items_pkey";

alter table "public"."stripe_invoice_line_items" add constraint "stripe_invoice_line_items_stripe_account_id_fkey" FOREIGN KEY (stripe_account_id) REFERENCES stripe_accounts(stripe_id) not valid;

alter table "public"."stripe_invoice_line_items" validate constraint "stripe_invoice_line_items_stripe_account_id_fkey";

alter table "public"."stripe_invoice_line_items" add constraint "stripe_invoice_line_items_stripe_id_key" UNIQUE using index "stripe_invoice_line_items_stripe_id_key";

alter table "public"."stripe_invoice_line_items" add constraint "stripe_invoice_line_items_stripe_invoice_id_fkey" FOREIGN KEY (stripe_invoice_id) REFERENCES stripe_invoices(stripe_id) ON DELETE CASCADE not valid;

alter table "public"."stripe_invoice_line_items" validate constraint "stripe_invoice_line_items_stripe_invoice_id_fkey";


