create table "public"."signups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "email" text not null
);


alter table "public"."signups" enable row level security;

CREATE UNIQUE INDEX signups_email_key ON public.signups USING btree (email);

CREATE UNIQUE INDEX signups_pkey ON public.signups USING btree (id);

alter table "public"."signups" add constraint "signups_pkey" PRIMARY KEY using index "signups_pkey";

alter table "public"."signups" add constraint "signups_email_key" UNIQUE using index "signups_email_key";


