create table "public"."sync_jobs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "live_mode_complete" boolean not null default false,
    "test_mode_complete" boolean not null default false,
    "stripe_account_id" text not null
);


alter table "public"."sync_jobs" enable row level security;

CREATE UNIQUE INDEX sync_jobs_pkey ON public.sync_jobs USING btree (id);

alter table "public"."sync_jobs" add constraint "sync_jobs_pkey" PRIMARY KEY using index "sync_jobs_pkey";

alter table "public"."sync_jobs" add constraint "sync_jobs_stripe_account_id_fkey" FOREIGN KEY (stripe_account_id) REFERENCES stripe_accounts(stripe_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sync_jobs" validate constraint "sync_jobs_stripe_account_id_fkey";

grant delete on table "public"."sync_jobs" to "anon";

grant insert on table "public"."sync_jobs" to "anon";

grant references on table "public"."sync_jobs" to "anon";

grant select on table "public"."sync_jobs" to "anon";

grant trigger on table "public"."sync_jobs" to "anon";

grant truncate on table "public"."sync_jobs" to "anon";

grant update on table "public"."sync_jobs" to "anon";

grant delete on table "public"."sync_jobs" to "authenticated";

grant insert on table "public"."sync_jobs" to "authenticated";

grant references on table "public"."sync_jobs" to "authenticated";

grant select on table "public"."sync_jobs" to "authenticated";

grant trigger on table "public"."sync_jobs" to "authenticated";

grant truncate on table "public"."sync_jobs" to "authenticated";

grant update on table "public"."sync_jobs" to "authenticated";

grant delete on table "public"."sync_jobs" to "service_role";

grant insert on table "public"."sync_jobs" to "service_role";

grant references on table "public"."sync_jobs" to "service_role";

grant select on table "public"."sync_jobs" to "service_role";

grant trigger on table "public"."sync_jobs" to "service_role";

grant truncate on table "public"."sync_jobs" to "service_role";

grant update on table "public"."sync_jobs" to "service_role";


