[build]
  command = "yarn build"
  functions = "netlify/functions"
  publish = ".next"

[[headers]]
  for = "/stripe/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/marketing/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.spackle.so"

[functions]
  external_node_modules = ["@sentry/serverless"]