name = "spackle-api"
compatibility_date = "2023-12-01"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
analytics_engine_datasets = [{ dataset = "entitlement-checks-development", binding = "ENTITLEMENT_CHECKS" }]

[vars]
ENVIRONMENT = "development"

[queues]
producers = [
  { queue = "sync-development", binding = "SYNC"},
]
consumers = [
  { queue = "sync-development", max_batch_size = 1, max_batch_timeout = 3, max_retries = 3 },
]


[env.production]
logpush = true
routes = [
  { pattern = "api.spackle.so", custom_domain = true },
  { pattern = "edge.spackle.so", custom_domain = true },
  { pattern = "us-east-1.edge.spackle.so", custom_domain = true },
  { pattern = "us-west-2.edge.spackle.so", custom_domain = true }
]
analytics_engine_datasets = [{ dataset = "entitlement-checks-production", binding = "ENTITLEMENT_CHECKS" }]

[env.production.vars]
ENVIRONMENT = "production"
HOST = "https://api.spackle.so"
POSTHOG_API_HOST = "https://app.posthog.com"
WEB_HOST = "https://www.spackle.so"

[env.production.queues]
producers = [
  { queue = "sync-production", binding = "SYNC"},
]
consumers = [
  { queue = "sync-production", max_batch_size = 1, max_batch_timeout = 3, max_retries = 3 },
]
