name: CI

on: push

env:
  SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs
  SUPABASE_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
  SUPABASE_URL: http://localhost:54321

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase start
      - name: Run tests
        run: yarn test