name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      supabase:
        image: supabase

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - uses: supabase/setup-cli@v1
      - run: supabase init
      - run: supabase start
      - name: Run tests
        run: yarn test